version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ ]
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    labels: [ ]
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /wasm_module
    labels: [ ]
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      cargo:
        patterns:
          - '*'