name: 'Deploy: Cloudflare PR Preview'
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  
env:
  PAGES_PROJECT_NAME: discretize-optimizer
  NODE_VERSION: 18
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write 

    # PRs must be from the same repository or GitHub will not supply secrets for security reasons.
    # This workflow should do nothing in those cases.
    # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.
    if: >
      github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name &&
      !contains(github.event.head_commit.message, 'skip ci') &&
      !contains(github.event.pull_request.body, '[no previews]') &&
      (contains(github.event.pull_request.body, '[draft previews]') || github.event.pull_request.draft == false)
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: wasm_module
      - name: Compile WASM
        run: pnpm wasm

      - name: Build Cloudflare
        run: pnpm build
        env:
          VITE_HAS_CF: true

      - name: Deploy preview to Cloudflare
        uses: cloudflare/wrangler-action@v3
        id: wrangler-action
        with:
          apiToken: ${{ secrets.CI_CF_PAGES }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: 3
          command: pages deploy dist --project-name=${{ env.PAGES_PROJECT_NAME }} --branch ${{ github.head_ref || github.ref_name }} 

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deployed ${{ steps.pages-action.outputs.environment }} build to Cloudflare!

            |                         |   |
            | ----------------------- | - |
            | **Last commit:**        | ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }} |
            | **Preview URL**:        | ${{ steps.wrangler-action.outputs.deployment-url }} |
            | **Branch Preview URL**: | https://${{ github.head_ref || github.ref_name }}.${{ env.PAGES_PROJECT_NAME }}.pages.dev |
          comment_tag: deployment
          mode: upsert
